//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Global.Portal.AuthServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemUserBase", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WMS.Global.Portal.AuthServiceReference.SystemUser))]
    public partial class SystemUserBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int SysNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisplayNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        private WMS.Global.Portal.AuthServiceReference.UserStatus StatusField;
        
        private int InUserField;
        
        private System.DateTime InDateField;
        
        private int EditUserField;
        
        private System.DateTime EditDateField;
        
        private int DepartmentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserDepartmentNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserDepartmentDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordSaltField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int SysNO {
            get {
                return this.SysNOField;
            }
            set {
                if ((this.SysNOField.Equals(value) != true)) {
                    this.SysNOField = value;
                    this.RaisePropertyChanged("SysNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string LoginName {
            get {
                return this.LoginNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginNameField, value) != true)) {
                    this.LoginNameField = value;
                    this.RaisePropertyChanged("LoginName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DisplayName {
            get {
                return this.DisplayNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplayNameField, value) != true)) {
                    this.DisplayNameField = value;
                    this.RaisePropertyChanged("DisplayName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string DepartmentName {
            get {
                return this.DepartmentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentNameField, value) != true)) {
                    this.DepartmentNameField = value;
                    this.RaisePropertyChanged("DepartmentName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public WMS.Global.Portal.AuthServiceReference.UserStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int InUser {
            get {
                return this.InUserField;
            }
            set {
                if ((this.InUserField.Equals(value) != true)) {
                    this.InUserField = value;
                    this.RaisePropertyChanged("InUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.DateTime InDate {
            get {
                return this.InDateField;
            }
            set {
                if ((this.InDateField.Equals(value) != true)) {
                    this.InDateField = value;
                    this.RaisePropertyChanged("InDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int EditUser {
            get {
                return this.EditUserField;
            }
            set {
                if ((this.EditUserField.Equals(value) != true)) {
                    this.EditUserField = value;
                    this.RaisePropertyChanged("EditUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public System.DateTime EditDate {
            get {
                return this.EditDateField;
            }
            set {
                if ((this.EditDateField.Equals(value) != true)) {
                    this.EditDateField = value;
                    this.RaisePropertyChanged("EditDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public int DepartmentID {
            get {
                return this.DepartmentIDField;
            }
            set {
                if ((this.DepartmentIDField.Equals(value) != true)) {
                    this.DepartmentIDField = value;
                    this.RaisePropertyChanged("DepartmentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string UserDepartmentName {
            get {
                return this.UserDepartmentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserDepartmentNameField, value) != true)) {
                    this.UserDepartmentNameField = value;
                    this.RaisePropertyChanged("UserDepartmentName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string UserDepartmentDescription {
            get {
                return this.UserDepartmentDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.UserDepartmentDescriptionField, value) != true)) {
                    this.UserDepartmentDescriptionField = value;
                    this.RaisePropertyChanged("UserDepartmentDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string PasswordSalt {
            get {
                return this.PasswordSaltField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordSaltField, value) != true)) {
                    this.PasswordSaltField = value;
                    this.RaisePropertyChanged("PasswordSalt");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemUser", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SystemUser : WMS.Global.Portal.AuthServiceReference.SystemUserBase {
        
        private int CompanySysNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CompanySysNO {
            get {
                return this.CompanySysNOField;
            }
            set {
                if ((this.CompanySysNOField.Equals(value) != true)) {
                    this.CompanySysNOField = value;
                    this.RaisePropertyChanged("CompanySysNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CompanyCode {
            get {
                return this.CompanyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyCodeField, value) != true)) {
                    this.CompanyCodeField = value;
                    this.RaisePropertyChanged("CompanyCode");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserStatus", Namespace="urn:Gznb.authcenter")]
    public enum UserStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Disabled = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Enabled = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemRole", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SystemRole : WMS.Global.Portal.AuthServiceReference.SystemRoleBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApplicationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WMS.Global.Portal.AuthServiceReference.SystemFunction[] FunctionListField;
        
        private bool UserHadField;
        
        private int CompanySysNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ApplicationName {
            get {
                return this.ApplicationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationNameField, value) != true)) {
                    this.ApplicationNameField = value;
                    this.RaisePropertyChanged("ApplicationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public WMS.Global.Portal.AuthServiceReference.SystemFunction[] FunctionList {
            get {
                return this.FunctionListField;
            }
            set {
                if ((object.ReferenceEquals(this.FunctionListField, value) != true)) {
                    this.FunctionListField = value;
                    this.RaisePropertyChanged("FunctionList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool UserHad {
            get {
                return this.UserHadField;
            }
            set {
                if ((this.UserHadField.Equals(value) != true)) {
                    this.UserHadField = value;
                    this.RaisePropertyChanged("UserHad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int CompanySysNO {
            get {
                return this.CompanySysNOField;
            }
            set {
                if ((this.CompanySysNOField.Equals(value) != true)) {
                    this.CompanySysNOField = value;
                    this.RaisePropertyChanged("CompanySysNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemRoleBase", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WMS.Global.Portal.AuthServiceReference.SystemRole))]
    public partial class SystemRoleBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int SysNOField;
        
        private System.Guid ApplicationIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomConditionField;
        
        private System.Nullable<int> ParentRoleSysNOField;
        
        private WMS.Global.Portal.AuthServiceReference.RoleStatus StatusField;
        
        private int InUserField;
        
        private System.DateTime InDateField;
        
        private int EditUserField;
        
        private System.DateTime EditDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int SysNO {
            get {
                return this.SysNOField;
            }
            set {
                if ((this.SysNOField.Equals(value) != true)) {
                    this.SysNOField = value;
                    this.RaisePropertyChanged("SysNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.Guid ApplicationID {
            get {
                return this.ApplicationIDField;
            }
            set {
                if ((this.ApplicationIDField.Equals(value) != true)) {
                    this.ApplicationIDField = value;
                    this.RaisePropertyChanged("ApplicationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string RoleName {
            get {
                return this.RoleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleNameField, value) != true)) {
                    this.RoleNameField = value;
                    this.RaisePropertyChanged("RoleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CustomCondition {
            get {
                return this.CustomConditionField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomConditionField, value) != true)) {
                    this.CustomConditionField = value;
                    this.RaisePropertyChanged("CustomCondition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<int> ParentRoleSysNO {
            get {
                return this.ParentRoleSysNOField;
            }
            set {
                if ((this.ParentRoleSysNOField.Equals(value) != true)) {
                    this.ParentRoleSysNOField = value;
                    this.RaisePropertyChanged("ParentRoleSysNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public WMS.Global.Portal.AuthServiceReference.RoleStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int InUser {
            get {
                return this.InUserField;
            }
            set {
                if ((this.InUserField.Equals(value) != true)) {
                    this.InUserField = value;
                    this.RaisePropertyChanged("InUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.DateTime InDate {
            get {
                return this.InDateField;
            }
            set {
                if ((this.InDateField.Equals(value) != true)) {
                    this.InDateField = value;
                    this.RaisePropertyChanged("InDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int EditUser {
            get {
                return this.EditUserField;
            }
            set {
                if ((this.EditUserField.Equals(value) != true)) {
                    this.EditUserField = value;
                    this.RaisePropertyChanged("EditUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public System.DateTime EditDate {
            get {
                return this.EditDateField;
            }
            set {
                if ((this.EditDateField.Equals(value) != true)) {
                    this.EditDateField = value;
                    this.RaisePropertyChanged("EditDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoleStatus", Namespace="http://tempuri.org/")]
    public enum RoleStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Disabled = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Enabled = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemFunction", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SystemFunction : WMS.Global.Portal.AuthServiceReference.SystemFunctionBase {
        
        private bool UserHadField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool UserHad {
            get {
                return this.UserHadField;
            }
            set {
                if ((this.UserHadField.Equals(value) != true)) {
                    this.UserHadField = value;
                    this.RaisePropertyChanged("UserHad");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemFunctionBase", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WMS.Global.Portal.AuthServiceReference.SystemFunction))]
    public partial class SystemFunctionBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int SysNOField;
        
        private System.Guid ApplicationIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthKeyField;
        
        private WMS.Global.Portal.AuthServiceReference.FunctionType TypeField;
        
        private WMS.Global.Portal.AuthServiceReference.FunctionStatus StatusField;
        
        private int InUserField;
        
        private System.DateTime InDateField;
        
        private int EditUserField;
        
        private System.DateTime EditDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int SysNO {
            get {
                return this.SysNOField;
            }
            set {
                if ((this.SysNOField.Equals(value) != true)) {
                    this.SysNOField = value;
                    this.RaisePropertyChanged("SysNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.Guid ApplicationID {
            get {
                return this.ApplicationIDField;
            }
            set {
                if ((this.ApplicationIDField.Equals(value) != true)) {
                    this.ApplicationIDField = value;
                    this.RaisePropertyChanged("ApplicationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string AuthKey {
            get {
                return this.AuthKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthKeyField, value) != true)) {
                    this.AuthKeyField = value;
                    this.RaisePropertyChanged("AuthKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public WMS.Global.Portal.AuthServiceReference.FunctionType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public WMS.Global.Portal.AuthServiceReference.FunctionStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int InUser {
            get {
                return this.InUserField;
            }
            set {
                if ((this.InUserField.Equals(value) != true)) {
                    this.InUserField = value;
                    this.RaisePropertyChanged("InUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.DateTime InDate {
            get {
                return this.InDateField;
            }
            set {
                if ((this.InDateField.Equals(value) != true)) {
                    this.InDateField = value;
                    this.RaisePropertyChanged("InDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int EditUser {
            get {
                return this.EditUserField;
            }
            set {
                if ((this.EditUserField.Equals(value) != true)) {
                    this.EditUserField = value;
                    this.RaisePropertyChanged("EditUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public System.DateTime EditDate {
            get {
                return this.EditDateField;
            }
            set {
                if ((this.EditDateField.Equals(value) != true)) {
                    this.EditDateField = value;
                    this.RaisePropertyChanged("EditDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FunctionType", Namespace="http://tempuri.org/")]
    public enum FunctionType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Page = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Button = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FunctionStatus", Namespace="http://tempuri.org/")]
    public enum FunctionStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Disabled = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Enabled = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AuthServiceReference.AuthServiceSoap")]
    public interface AuthServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 loginName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        WMS.Global.Portal.AuthServiceReference.LoginResponse Login(WMS.Global.Portal.AuthServiceReference.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<WMS.Global.Portal.AuthServiceReference.LoginResponse> LoginAsync(WMS.Global.Portal.AuthServiceReference.LoginRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 loginName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginAuth", ReplyAction="*")]
        WMS.Global.Portal.AuthServiceReference.LoginAuthResponse LoginAuth(WMS.Global.Portal.AuthServiceReference.LoginAuthRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginAuth", ReplyAction="*")]
        System.Threading.Tasks.Task<WMS.Global.Portal.AuthServiceReference.LoginAuthResponse> LoginAuthAsync(WMS.Global.Portal.AuthServiceReference.LoginAuthRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 loginName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TrustedLogin", ReplyAction="*")]
        WMS.Global.Portal.AuthServiceReference.TrustedLoginResponse TrustedLogin(WMS.Global.Portal.AuthServiceReference.TrustedLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TrustedLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<WMS.Global.Portal.AuthServiceReference.TrustedLoginResponse> TrustedLoginAsync(WMS.Global.Portal.AuthServiceReference.TrustedLoginRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 loginName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangePassword", ReplyAction="*")]
        WMS.Global.Portal.AuthServiceReference.ChangePasswordResponse ChangePassword(WMS.Global.Portal.AuthServiceReference.ChangePasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangePassword", ReplyAction="*")]
        System.Threading.Tasks.Task<WMS.Global.Portal.AuthServiceReference.ChangePasswordResponse> ChangePasswordAsync(WMS.Global.Portal.AuthServiceReference.ChangePasswordRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 applicationID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserFunction", ReplyAction="*")]
        WMS.Global.Portal.AuthServiceReference.GetUserFunctionResponse GetUserFunction(WMS.Global.Portal.AuthServiceReference.GetUserFunctionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserFunction", ReplyAction="*")]
        System.Threading.Tasks.Task<WMS.Global.Portal.AuthServiceReference.GetUserFunctionResponse> GetUserFunctionAsync(WMS.Global.Portal.AuthServiceReference.GetUserFunctionRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 applicationID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserAuthKey", ReplyAction="*")]
        WMS.Global.Portal.AuthServiceReference.GetUserAuthKeyResponse GetUserAuthKey(WMS.Global.Portal.AuthServiceReference.GetUserAuthKeyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserAuthKey", ReplyAction="*")]
        System.Threading.Tasks.Task<WMS.Global.Portal.AuthServiceReference.GetUserAuthKeyResponse> GetUserAuthKeyAsync(WMS.Global.Portal.AuthServiceReference.GetUserAuthKeyRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 applicationID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckUserFunction", ReplyAction="*")]
        WMS.Global.Portal.AuthServiceReference.CheckUserFunctionResponse CheckUserFunction(WMS.Global.Portal.AuthServiceReference.CheckUserFunctionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckUserFunction", ReplyAction="*")]
        System.Threading.Tasks.Task<WMS.Global.Portal.AuthServiceReference.CheckUserFunctionResponse> CheckUserFunctionAsync(WMS.Global.Portal.AuthServiceReference.CheckUserFunctionRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 applicationID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSystemUserByApplicationID", ReplyAction="*")]
        WMS.Global.Portal.AuthServiceReference.GetSystemUserByApplicationIDResponse GetSystemUserByApplicationID(WMS.Global.Portal.AuthServiceReference.GetSystemUserByApplicationIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSystemUserByApplicationID", ReplyAction="*")]
        System.Threading.Tasks.Task<WMS.Global.Portal.AuthServiceReference.GetSystemUserByApplicationIDResponse> GetSystemUserByApplicationIDAsync(WMS.Global.Portal.AuthServiceReference.GetSystemUserByApplicationIDRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 GetSystemUserBySysNoResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSystemUserBySysNo", ReplyAction="*")]
        WMS.Global.Portal.AuthServiceReference.GetSystemUserBySysNoResponse GetSystemUserBySysNo(WMS.Global.Portal.AuthServiceReference.GetSystemUserBySysNoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSystemUserBySysNo", ReplyAction="*")]
        System.Threading.Tasks.Task<WMS.Global.Portal.AuthServiceReference.GetSystemUserBySysNoResponse> GetSystemUserBySysNoAsync(WMS.Global.Portal.AuthServiceReference.GetSystemUserBySysNoRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 loginName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSystemUserByLoginName", ReplyAction="*")]
        WMS.Global.Portal.AuthServiceReference.GetSystemUserByLoginNameResponse GetSystemUserByLoginName(WMS.Global.Portal.AuthServiceReference.GetSystemUserByLoginNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSystemUserByLoginName", ReplyAction="*")]
        System.Threading.Tasks.Task<WMS.Global.Portal.AuthServiceReference.GetSystemUserByLoginNameResponse> GetSystemUserByLoginNameAsync(WMS.Global.Portal.AuthServiceReference.GetSystemUserByLoginNameRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public WMS.Global.Portal.AuthServiceReference.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(WMS.Global.Portal.AuthServiceReference.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string loginName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string loginName, string password) {
            this.loginName = loginName;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public WMS.Global.Portal.AuthServiceReference.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(WMS.Global.Portal.AuthServiceReference.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WMS.Global.Portal.AuthServiceReference.SystemUser LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(WMS.Global.Portal.AuthServiceReference.SystemUser LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginAuthRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginAuth", Namespace="http://tempuri.org/", Order=0)]
        public WMS.Global.Portal.AuthServiceReference.LoginAuthRequestBody Body;
        
        public LoginAuthRequest() {
        }
        
        public LoginAuthRequest(WMS.Global.Portal.AuthServiceReference.LoginAuthRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginAuthRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string loginName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public LoginAuthRequestBody() {
        }
        
        public LoginAuthRequestBody(string loginName, string password) {
            this.loginName = loginName;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginAuthResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginAuthResponse", Namespace="http://tempuri.org/", Order=0)]
        public WMS.Global.Portal.AuthServiceReference.LoginAuthResponseBody Body;
        
        public LoginAuthResponse() {
        }
        
        public LoginAuthResponse(WMS.Global.Portal.AuthServiceReference.LoginAuthResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginAuthResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WMS.Global.Portal.AuthServiceReference.SystemUser LoginAuthResult;
        
        public LoginAuthResponseBody() {
        }
        
        public LoginAuthResponseBody(WMS.Global.Portal.AuthServiceReference.SystemUser LoginAuthResult) {
            this.LoginAuthResult = LoginAuthResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TrustedLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TrustedLogin", Namespace="http://tempuri.org/", Order=0)]
        public WMS.Global.Portal.AuthServiceReference.TrustedLoginRequestBody Body;
        
        public TrustedLoginRequest() {
        }
        
        public TrustedLoginRequest(WMS.Global.Portal.AuthServiceReference.TrustedLoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TrustedLoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string loginName;
        
        public TrustedLoginRequestBody() {
        }
        
        public TrustedLoginRequestBody(string loginName) {
            this.loginName = loginName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TrustedLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TrustedLoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public WMS.Global.Portal.AuthServiceReference.TrustedLoginResponseBody Body;
        
        public TrustedLoginResponse() {
        }
        
        public TrustedLoginResponse(WMS.Global.Portal.AuthServiceReference.TrustedLoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TrustedLoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WMS.Global.Portal.AuthServiceReference.SystemUser TrustedLoginResult;
        
        public TrustedLoginResponseBody() {
        }
        
        public TrustedLoginResponseBody(WMS.Global.Portal.AuthServiceReference.SystemUser TrustedLoginResult) {
            this.TrustedLoginResult = TrustedLoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangePasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangePassword", Namespace="http://tempuri.org/", Order=0)]
        public WMS.Global.Portal.AuthServiceReference.ChangePasswordRequestBody Body;
        
        public ChangePasswordRequest() {
        }
        
        public ChangePasswordRequest(WMS.Global.Portal.AuthServiceReference.ChangePasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChangePasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string loginName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string oldPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string newPassword;
        
        public ChangePasswordRequestBody() {
        }
        
        public ChangePasswordRequestBody(string loginName, string oldPassword, string newPassword) {
            this.loginName = loginName;
            this.oldPassword = oldPassword;
            this.newPassword = newPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangePasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangePasswordResponse", Namespace="http://tempuri.org/", Order=0)]
        public WMS.Global.Portal.AuthServiceReference.ChangePasswordResponseBody Body;
        
        public ChangePasswordResponse() {
        }
        
        public ChangePasswordResponse(WMS.Global.Portal.AuthServiceReference.ChangePasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChangePasswordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WMS.Global.Portal.AuthServiceReference.SystemUser ChangePasswordResult;
        
        public ChangePasswordResponseBody() {
        }
        
        public ChangePasswordResponseBody(WMS.Global.Portal.AuthServiceReference.SystemUser ChangePasswordResult) {
            this.ChangePasswordResult = ChangePasswordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserFunctionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserFunction", Namespace="http://tempuri.org/", Order=0)]
        public WMS.Global.Portal.AuthServiceReference.GetUserFunctionRequestBody Body;
        
        public GetUserFunctionRequest() {
        }
        
        public GetUserFunctionRequest(WMS.Global.Portal.AuthServiceReference.GetUserFunctionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserFunctionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string applicationID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string loginName;
        
        public GetUserFunctionRequestBody() {
        }
        
        public GetUserFunctionRequestBody(string applicationID, string loginName) {
            this.applicationID = applicationID;
            this.loginName = loginName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserFunctionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserFunctionResponse", Namespace="http://tempuri.org/", Order=0)]
        public WMS.Global.Portal.AuthServiceReference.GetUserFunctionResponseBody Body;
        
        public GetUserFunctionResponse() {
        }
        
        public GetUserFunctionResponse(WMS.Global.Portal.AuthServiceReference.GetUserFunctionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserFunctionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WMS.Global.Portal.AuthServiceReference.SystemRole[] GetUserFunctionResult;
        
        public GetUserFunctionResponseBody() {
        }
        
        public GetUserFunctionResponseBody(WMS.Global.Portal.AuthServiceReference.SystemRole[] GetUserFunctionResult) {
            this.GetUserFunctionResult = GetUserFunctionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserAuthKeyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserAuthKey", Namespace="http://tempuri.org/", Order=0)]
        public WMS.Global.Portal.AuthServiceReference.GetUserAuthKeyRequestBody Body;
        
        public GetUserAuthKeyRequest() {
        }
        
        public GetUserAuthKeyRequest(WMS.Global.Portal.AuthServiceReference.GetUserAuthKeyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserAuthKeyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string applicationID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string loginName;
        
        public GetUserAuthKeyRequestBody() {
        }
        
        public GetUserAuthKeyRequestBody(string applicationID, string loginName) {
            this.applicationID = applicationID;
            this.loginName = loginName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserAuthKeyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserAuthKeyResponse", Namespace="http://tempuri.org/", Order=0)]
        public WMS.Global.Portal.AuthServiceReference.GetUserAuthKeyResponseBody Body;
        
        public GetUserAuthKeyResponse() {
        }
        
        public GetUserAuthKeyResponse(WMS.Global.Portal.AuthServiceReference.GetUserAuthKeyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserAuthKeyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WMS.Global.Portal.AuthServiceReference.ArrayOfString GetUserAuthKeyResult;
        
        public GetUserAuthKeyResponseBody() {
        }
        
        public GetUserAuthKeyResponseBody(WMS.Global.Portal.AuthServiceReference.ArrayOfString GetUserAuthKeyResult) {
            this.GetUserAuthKeyResult = GetUserAuthKeyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckUserFunctionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckUserFunction", Namespace="http://tempuri.org/", Order=0)]
        public WMS.Global.Portal.AuthServiceReference.CheckUserFunctionRequestBody Body;
        
        public CheckUserFunctionRequest() {
        }
        
        public CheckUserFunctionRequest(WMS.Global.Portal.AuthServiceReference.CheckUserFunctionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckUserFunctionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string applicationID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string authKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string loginName;
        
        public CheckUserFunctionRequestBody() {
        }
        
        public CheckUserFunctionRequestBody(string applicationID, string authKey, string loginName) {
            this.applicationID = applicationID;
            this.authKey = authKey;
            this.loginName = loginName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckUserFunctionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckUserFunctionResponse", Namespace="http://tempuri.org/", Order=0)]
        public WMS.Global.Portal.AuthServiceReference.CheckUserFunctionResponseBody Body;
        
        public CheckUserFunctionResponse() {
        }
        
        public CheckUserFunctionResponse(WMS.Global.Portal.AuthServiceReference.CheckUserFunctionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckUserFunctionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CheckUserFunctionResult;
        
        public CheckUserFunctionResponseBody() {
        }
        
        public CheckUserFunctionResponseBody(bool CheckUserFunctionResult) {
            this.CheckUserFunctionResult = CheckUserFunctionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSystemUserByApplicationIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSystemUserByApplicationID", Namespace="http://tempuri.org/", Order=0)]
        public WMS.Global.Portal.AuthServiceReference.GetSystemUserByApplicationIDRequestBody Body;
        
        public GetSystemUserByApplicationIDRequest() {
        }
        
        public GetSystemUserByApplicationIDRequest(WMS.Global.Portal.AuthServiceReference.GetSystemUserByApplicationIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSystemUserByApplicationIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string applicationID;
        
        public GetSystemUserByApplicationIDRequestBody() {
        }
        
        public GetSystemUserByApplicationIDRequestBody(string applicationID) {
            this.applicationID = applicationID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSystemUserByApplicationIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSystemUserByApplicationIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public WMS.Global.Portal.AuthServiceReference.GetSystemUserByApplicationIDResponseBody Body;
        
        public GetSystemUserByApplicationIDResponse() {
        }
        
        public GetSystemUserByApplicationIDResponse(WMS.Global.Portal.AuthServiceReference.GetSystemUserByApplicationIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSystemUserByApplicationIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WMS.Global.Portal.AuthServiceReference.SystemUser[] GetSystemUserByApplicationIDResult;
        
        public GetSystemUserByApplicationIDResponseBody() {
        }
        
        public GetSystemUserByApplicationIDResponseBody(WMS.Global.Portal.AuthServiceReference.SystemUser[] GetSystemUserByApplicationIDResult) {
            this.GetSystemUserByApplicationIDResult = GetSystemUserByApplicationIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSystemUserBySysNoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSystemUserBySysNo", Namespace="http://tempuri.org/", Order=0)]
        public WMS.Global.Portal.AuthServiceReference.GetSystemUserBySysNoRequestBody Body;
        
        public GetSystemUserBySysNoRequest() {
        }
        
        public GetSystemUserBySysNoRequest(WMS.Global.Portal.AuthServiceReference.GetSystemUserBySysNoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSystemUserBySysNoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int sysNo;
        
        public GetSystemUserBySysNoRequestBody() {
        }
        
        public GetSystemUserBySysNoRequestBody(int sysNo) {
            this.sysNo = sysNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSystemUserBySysNoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSystemUserBySysNoResponse", Namespace="http://tempuri.org/", Order=0)]
        public WMS.Global.Portal.AuthServiceReference.GetSystemUserBySysNoResponseBody Body;
        
        public GetSystemUserBySysNoResponse() {
        }
        
        public GetSystemUserBySysNoResponse(WMS.Global.Portal.AuthServiceReference.GetSystemUserBySysNoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSystemUserBySysNoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WMS.Global.Portal.AuthServiceReference.SystemUser GetSystemUserBySysNoResult;
        
        public GetSystemUserBySysNoResponseBody() {
        }
        
        public GetSystemUserBySysNoResponseBody(WMS.Global.Portal.AuthServiceReference.SystemUser GetSystemUserBySysNoResult) {
            this.GetSystemUserBySysNoResult = GetSystemUserBySysNoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSystemUserByLoginNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSystemUserByLoginName", Namespace="http://tempuri.org/", Order=0)]
        public WMS.Global.Portal.AuthServiceReference.GetSystemUserByLoginNameRequestBody Body;
        
        public GetSystemUserByLoginNameRequest() {
        }
        
        public GetSystemUserByLoginNameRequest(WMS.Global.Portal.AuthServiceReference.GetSystemUserByLoginNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSystemUserByLoginNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string loginName;
        
        public GetSystemUserByLoginNameRequestBody() {
        }
        
        public GetSystemUserByLoginNameRequestBody(string loginName) {
            this.loginName = loginName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSystemUserByLoginNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSystemUserByLoginNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public WMS.Global.Portal.AuthServiceReference.GetSystemUserByLoginNameResponseBody Body;
        
        public GetSystemUserByLoginNameResponse() {
        }
        
        public GetSystemUserByLoginNameResponse(WMS.Global.Portal.AuthServiceReference.GetSystemUserByLoginNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSystemUserByLoginNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WMS.Global.Portal.AuthServiceReference.SystemUser GetSystemUserByLoginNameResult;
        
        public GetSystemUserByLoginNameResponseBody() {
        }
        
        public GetSystemUserByLoginNameResponseBody(WMS.Global.Portal.AuthServiceReference.SystemUser GetSystemUserByLoginNameResult) {
            this.GetSystemUserByLoginNameResult = GetSystemUserByLoginNameResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AuthServiceSoapChannel : WMS.Global.Portal.AuthServiceReference.AuthServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthServiceSoapClient : System.ServiceModel.ClientBase<WMS.Global.Portal.AuthServiceReference.AuthServiceSoap>, WMS.Global.Portal.AuthServiceReference.AuthServiceSoap {
        
        public AuthServiceSoapClient() {
        }
        
        public AuthServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WMS.Global.Portal.AuthServiceReference.LoginResponse WMS.Global.Portal.AuthServiceReference.AuthServiceSoap.Login(WMS.Global.Portal.AuthServiceReference.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public WMS.Global.Portal.AuthServiceReference.SystemUser Login(string loginName, string password) {
            WMS.Global.Portal.AuthServiceReference.LoginRequest inValue = new WMS.Global.Portal.AuthServiceReference.LoginRequest();
            inValue.Body = new WMS.Global.Portal.AuthServiceReference.LoginRequestBody();
            inValue.Body.loginName = loginName;
            inValue.Body.password = password;
            WMS.Global.Portal.AuthServiceReference.LoginResponse retVal = ((WMS.Global.Portal.AuthServiceReference.AuthServiceSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WMS.Global.Portal.AuthServiceReference.LoginResponse> WMS.Global.Portal.AuthServiceReference.AuthServiceSoap.LoginAsync(WMS.Global.Portal.AuthServiceReference.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<WMS.Global.Portal.AuthServiceReference.LoginResponse> LoginAsync(string loginName, string password) {
            WMS.Global.Portal.AuthServiceReference.LoginRequest inValue = new WMS.Global.Portal.AuthServiceReference.LoginRequest();
            inValue.Body = new WMS.Global.Portal.AuthServiceReference.LoginRequestBody();
            inValue.Body.loginName = loginName;
            inValue.Body.password = password;
            return ((WMS.Global.Portal.AuthServiceReference.AuthServiceSoap)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WMS.Global.Portal.AuthServiceReference.LoginAuthResponse WMS.Global.Portal.AuthServiceReference.AuthServiceSoap.LoginAuth(WMS.Global.Portal.AuthServiceReference.LoginAuthRequest request) {
            return base.Channel.LoginAuth(request);
        }
        
        public WMS.Global.Portal.AuthServiceReference.SystemUser LoginAuth(string loginName, string password) {
            WMS.Global.Portal.AuthServiceReference.LoginAuthRequest inValue = new WMS.Global.Portal.AuthServiceReference.LoginAuthRequest();
            inValue.Body = new WMS.Global.Portal.AuthServiceReference.LoginAuthRequestBody();
            inValue.Body.loginName = loginName;
            inValue.Body.password = password;
            WMS.Global.Portal.AuthServiceReference.LoginAuthResponse retVal = ((WMS.Global.Portal.AuthServiceReference.AuthServiceSoap)(this)).LoginAuth(inValue);
            return retVal.Body.LoginAuthResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WMS.Global.Portal.AuthServiceReference.LoginAuthResponse> WMS.Global.Portal.AuthServiceReference.AuthServiceSoap.LoginAuthAsync(WMS.Global.Portal.AuthServiceReference.LoginAuthRequest request) {
            return base.Channel.LoginAuthAsync(request);
        }
        
        public System.Threading.Tasks.Task<WMS.Global.Portal.AuthServiceReference.LoginAuthResponse> LoginAuthAsync(string loginName, string password) {
            WMS.Global.Portal.AuthServiceReference.LoginAuthRequest inValue = new WMS.Global.Portal.AuthServiceReference.LoginAuthRequest();
            inValue.Body = new WMS.Global.Portal.AuthServiceReference.LoginAuthRequestBody();
            inValue.Body.loginName = loginName;
            inValue.Body.password = password;
            return ((WMS.Global.Portal.AuthServiceReference.AuthServiceSoap)(this)).LoginAuthAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WMS.Global.Portal.AuthServiceReference.TrustedLoginResponse WMS.Global.Portal.AuthServiceReference.AuthServiceSoap.TrustedLogin(WMS.Global.Portal.AuthServiceReference.TrustedLoginRequest request) {
            return base.Channel.TrustedLogin(request);
        }
        
        public WMS.Global.Portal.AuthServiceReference.SystemUser TrustedLogin(string loginName) {
            WMS.Global.Portal.AuthServiceReference.TrustedLoginRequest inValue = new WMS.Global.Portal.AuthServiceReference.TrustedLoginRequest();
            inValue.Body = new WMS.Global.Portal.AuthServiceReference.TrustedLoginRequestBody();
            inValue.Body.loginName = loginName;
            WMS.Global.Portal.AuthServiceReference.TrustedLoginResponse retVal = ((WMS.Global.Portal.AuthServiceReference.AuthServiceSoap)(this)).TrustedLogin(inValue);
            return retVal.Body.TrustedLoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WMS.Global.Portal.AuthServiceReference.TrustedLoginResponse> WMS.Global.Portal.AuthServiceReference.AuthServiceSoap.TrustedLoginAsync(WMS.Global.Portal.AuthServiceReference.TrustedLoginRequest request) {
            return base.Channel.TrustedLoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<WMS.Global.Portal.AuthServiceReference.TrustedLoginResponse> TrustedLoginAsync(string loginName) {
            WMS.Global.Portal.AuthServiceReference.TrustedLoginRequest inValue = new WMS.Global.Portal.AuthServiceReference.TrustedLoginRequest();
            inValue.Body = new WMS.Global.Portal.AuthServiceReference.TrustedLoginRequestBody();
            inValue.Body.loginName = loginName;
            return ((WMS.Global.Portal.AuthServiceReference.AuthServiceSoap)(this)).TrustedLoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WMS.Global.Portal.AuthServiceReference.ChangePasswordResponse WMS.Global.Portal.AuthServiceReference.AuthServiceSoap.ChangePassword(WMS.Global.Portal.AuthServiceReference.ChangePasswordRequest request) {
            return base.Channel.ChangePassword(request);
        }
        
        public WMS.Global.Portal.AuthServiceReference.SystemUser ChangePassword(string loginName, string oldPassword, string newPassword) {
            WMS.Global.Portal.AuthServiceReference.ChangePasswordRequest inValue = new WMS.Global.Portal.AuthServiceReference.ChangePasswordRequest();
            inValue.Body = new WMS.Global.Portal.AuthServiceReference.ChangePasswordRequestBody();
            inValue.Body.loginName = loginName;
            inValue.Body.oldPassword = oldPassword;
            inValue.Body.newPassword = newPassword;
            WMS.Global.Portal.AuthServiceReference.ChangePasswordResponse retVal = ((WMS.Global.Portal.AuthServiceReference.AuthServiceSoap)(this)).ChangePassword(inValue);
            return retVal.Body.ChangePasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WMS.Global.Portal.AuthServiceReference.ChangePasswordResponse> WMS.Global.Portal.AuthServiceReference.AuthServiceSoap.ChangePasswordAsync(WMS.Global.Portal.AuthServiceReference.ChangePasswordRequest request) {
            return base.Channel.ChangePasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<WMS.Global.Portal.AuthServiceReference.ChangePasswordResponse> ChangePasswordAsync(string loginName, string oldPassword, string newPassword) {
            WMS.Global.Portal.AuthServiceReference.ChangePasswordRequest inValue = new WMS.Global.Portal.AuthServiceReference.ChangePasswordRequest();
            inValue.Body = new WMS.Global.Portal.AuthServiceReference.ChangePasswordRequestBody();
            inValue.Body.loginName = loginName;
            inValue.Body.oldPassword = oldPassword;
            inValue.Body.newPassword = newPassword;
            return ((WMS.Global.Portal.AuthServiceReference.AuthServiceSoap)(this)).ChangePasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WMS.Global.Portal.AuthServiceReference.GetUserFunctionResponse WMS.Global.Portal.AuthServiceReference.AuthServiceSoap.GetUserFunction(WMS.Global.Portal.AuthServiceReference.GetUserFunctionRequest request) {
            return base.Channel.GetUserFunction(request);
        }
        
        public WMS.Global.Portal.AuthServiceReference.SystemRole[] GetUserFunction(string applicationID, string loginName) {
            WMS.Global.Portal.AuthServiceReference.GetUserFunctionRequest inValue = new WMS.Global.Portal.AuthServiceReference.GetUserFunctionRequest();
            inValue.Body = new WMS.Global.Portal.AuthServiceReference.GetUserFunctionRequestBody();
            inValue.Body.applicationID = applicationID;
            inValue.Body.loginName = loginName;
            WMS.Global.Portal.AuthServiceReference.GetUserFunctionResponse retVal = ((WMS.Global.Portal.AuthServiceReference.AuthServiceSoap)(this)).GetUserFunction(inValue);
            return retVal.Body.GetUserFunctionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WMS.Global.Portal.AuthServiceReference.GetUserFunctionResponse> WMS.Global.Portal.AuthServiceReference.AuthServiceSoap.GetUserFunctionAsync(WMS.Global.Portal.AuthServiceReference.GetUserFunctionRequest request) {
            return base.Channel.GetUserFunctionAsync(request);
        }
        
        public System.Threading.Tasks.Task<WMS.Global.Portal.AuthServiceReference.GetUserFunctionResponse> GetUserFunctionAsync(string applicationID, string loginName) {
            WMS.Global.Portal.AuthServiceReference.GetUserFunctionRequest inValue = new WMS.Global.Portal.AuthServiceReference.GetUserFunctionRequest();
            inValue.Body = new WMS.Global.Portal.AuthServiceReference.GetUserFunctionRequestBody();
            inValue.Body.applicationID = applicationID;
            inValue.Body.loginName = loginName;
            return ((WMS.Global.Portal.AuthServiceReference.AuthServiceSoap)(this)).GetUserFunctionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WMS.Global.Portal.AuthServiceReference.GetUserAuthKeyResponse WMS.Global.Portal.AuthServiceReference.AuthServiceSoap.GetUserAuthKey(WMS.Global.Portal.AuthServiceReference.GetUserAuthKeyRequest request) {
            return base.Channel.GetUserAuthKey(request);
        }
        
        public WMS.Global.Portal.AuthServiceReference.ArrayOfString GetUserAuthKey(string applicationID, string loginName) {
            WMS.Global.Portal.AuthServiceReference.GetUserAuthKeyRequest inValue = new WMS.Global.Portal.AuthServiceReference.GetUserAuthKeyRequest();
            inValue.Body = new WMS.Global.Portal.AuthServiceReference.GetUserAuthKeyRequestBody();
            inValue.Body.applicationID = applicationID;
            inValue.Body.loginName = loginName;
            WMS.Global.Portal.AuthServiceReference.GetUserAuthKeyResponse retVal = ((WMS.Global.Portal.AuthServiceReference.AuthServiceSoap)(this)).GetUserAuthKey(inValue);
            return retVal.Body.GetUserAuthKeyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WMS.Global.Portal.AuthServiceReference.GetUserAuthKeyResponse> WMS.Global.Portal.AuthServiceReference.AuthServiceSoap.GetUserAuthKeyAsync(WMS.Global.Portal.AuthServiceReference.GetUserAuthKeyRequest request) {
            return base.Channel.GetUserAuthKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<WMS.Global.Portal.AuthServiceReference.GetUserAuthKeyResponse> GetUserAuthKeyAsync(string applicationID, string loginName) {
            WMS.Global.Portal.AuthServiceReference.GetUserAuthKeyRequest inValue = new WMS.Global.Portal.AuthServiceReference.GetUserAuthKeyRequest();
            inValue.Body = new WMS.Global.Portal.AuthServiceReference.GetUserAuthKeyRequestBody();
            inValue.Body.applicationID = applicationID;
            inValue.Body.loginName = loginName;
            return ((WMS.Global.Portal.AuthServiceReference.AuthServiceSoap)(this)).GetUserAuthKeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WMS.Global.Portal.AuthServiceReference.CheckUserFunctionResponse WMS.Global.Portal.AuthServiceReference.AuthServiceSoap.CheckUserFunction(WMS.Global.Portal.AuthServiceReference.CheckUserFunctionRequest request) {
            return base.Channel.CheckUserFunction(request);
        }
        
        public bool CheckUserFunction(string applicationID, string authKey, string loginName) {
            WMS.Global.Portal.AuthServiceReference.CheckUserFunctionRequest inValue = new WMS.Global.Portal.AuthServiceReference.CheckUserFunctionRequest();
            inValue.Body = new WMS.Global.Portal.AuthServiceReference.CheckUserFunctionRequestBody();
            inValue.Body.applicationID = applicationID;
            inValue.Body.authKey = authKey;
            inValue.Body.loginName = loginName;
            WMS.Global.Portal.AuthServiceReference.CheckUserFunctionResponse retVal = ((WMS.Global.Portal.AuthServiceReference.AuthServiceSoap)(this)).CheckUserFunction(inValue);
            return retVal.Body.CheckUserFunctionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WMS.Global.Portal.AuthServiceReference.CheckUserFunctionResponse> WMS.Global.Portal.AuthServiceReference.AuthServiceSoap.CheckUserFunctionAsync(WMS.Global.Portal.AuthServiceReference.CheckUserFunctionRequest request) {
            return base.Channel.CheckUserFunctionAsync(request);
        }
        
        public System.Threading.Tasks.Task<WMS.Global.Portal.AuthServiceReference.CheckUserFunctionResponse> CheckUserFunctionAsync(string applicationID, string authKey, string loginName) {
            WMS.Global.Portal.AuthServiceReference.CheckUserFunctionRequest inValue = new WMS.Global.Portal.AuthServiceReference.CheckUserFunctionRequest();
            inValue.Body = new WMS.Global.Portal.AuthServiceReference.CheckUserFunctionRequestBody();
            inValue.Body.applicationID = applicationID;
            inValue.Body.authKey = authKey;
            inValue.Body.loginName = loginName;
            return ((WMS.Global.Portal.AuthServiceReference.AuthServiceSoap)(this)).CheckUserFunctionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WMS.Global.Portal.AuthServiceReference.GetSystemUserByApplicationIDResponse WMS.Global.Portal.AuthServiceReference.AuthServiceSoap.GetSystemUserByApplicationID(WMS.Global.Portal.AuthServiceReference.GetSystemUserByApplicationIDRequest request) {
            return base.Channel.GetSystemUserByApplicationID(request);
        }
        
        public WMS.Global.Portal.AuthServiceReference.SystemUser[] GetSystemUserByApplicationID(string applicationID) {
            WMS.Global.Portal.AuthServiceReference.GetSystemUserByApplicationIDRequest inValue = new WMS.Global.Portal.AuthServiceReference.GetSystemUserByApplicationIDRequest();
            inValue.Body = new WMS.Global.Portal.AuthServiceReference.GetSystemUserByApplicationIDRequestBody();
            inValue.Body.applicationID = applicationID;
            WMS.Global.Portal.AuthServiceReference.GetSystemUserByApplicationIDResponse retVal = ((WMS.Global.Portal.AuthServiceReference.AuthServiceSoap)(this)).GetSystemUserByApplicationID(inValue);
            return retVal.Body.GetSystemUserByApplicationIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WMS.Global.Portal.AuthServiceReference.GetSystemUserByApplicationIDResponse> WMS.Global.Portal.AuthServiceReference.AuthServiceSoap.GetSystemUserByApplicationIDAsync(WMS.Global.Portal.AuthServiceReference.GetSystemUserByApplicationIDRequest request) {
            return base.Channel.GetSystemUserByApplicationIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<WMS.Global.Portal.AuthServiceReference.GetSystemUserByApplicationIDResponse> GetSystemUserByApplicationIDAsync(string applicationID) {
            WMS.Global.Portal.AuthServiceReference.GetSystemUserByApplicationIDRequest inValue = new WMS.Global.Portal.AuthServiceReference.GetSystemUserByApplicationIDRequest();
            inValue.Body = new WMS.Global.Portal.AuthServiceReference.GetSystemUserByApplicationIDRequestBody();
            inValue.Body.applicationID = applicationID;
            return ((WMS.Global.Portal.AuthServiceReference.AuthServiceSoap)(this)).GetSystemUserByApplicationIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WMS.Global.Portal.AuthServiceReference.GetSystemUserBySysNoResponse WMS.Global.Portal.AuthServiceReference.AuthServiceSoap.GetSystemUserBySysNo(WMS.Global.Portal.AuthServiceReference.GetSystemUserBySysNoRequest request) {
            return base.Channel.GetSystemUserBySysNo(request);
        }
        
        public WMS.Global.Portal.AuthServiceReference.SystemUser GetSystemUserBySysNo(int sysNo) {
            WMS.Global.Portal.AuthServiceReference.GetSystemUserBySysNoRequest inValue = new WMS.Global.Portal.AuthServiceReference.GetSystemUserBySysNoRequest();
            inValue.Body = new WMS.Global.Portal.AuthServiceReference.GetSystemUserBySysNoRequestBody();
            inValue.Body.sysNo = sysNo;
            WMS.Global.Portal.AuthServiceReference.GetSystemUserBySysNoResponse retVal = ((WMS.Global.Portal.AuthServiceReference.AuthServiceSoap)(this)).GetSystemUserBySysNo(inValue);
            return retVal.Body.GetSystemUserBySysNoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WMS.Global.Portal.AuthServiceReference.GetSystemUserBySysNoResponse> WMS.Global.Portal.AuthServiceReference.AuthServiceSoap.GetSystemUserBySysNoAsync(WMS.Global.Portal.AuthServiceReference.GetSystemUserBySysNoRequest request) {
            return base.Channel.GetSystemUserBySysNoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WMS.Global.Portal.AuthServiceReference.GetSystemUserBySysNoResponse> GetSystemUserBySysNoAsync(int sysNo) {
            WMS.Global.Portal.AuthServiceReference.GetSystemUserBySysNoRequest inValue = new WMS.Global.Portal.AuthServiceReference.GetSystemUserBySysNoRequest();
            inValue.Body = new WMS.Global.Portal.AuthServiceReference.GetSystemUserBySysNoRequestBody();
            inValue.Body.sysNo = sysNo;
            return ((WMS.Global.Portal.AuthServiceReference.AuthServiceSoap)(this)).GetSystemUserBySysNoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WMS.Global.Portal.AuthServiceReference.GetSystemUserByLoginNameResponse WMS.Global.Portal.AuthServiceReference.AuthServiceSoap.GetSystemUserByLoginName(WMS.Global.Portal.AuthServiceReference.GetSystemUserByLoginNameRequest request) {
            return base.Channel.GetSystemUserByLoginName(request);
        }
        
        public WMS.Global.Portal.AuthServiceReference.SystemUser GetSystemUserByLoginName(string loginName) {
            WMS.Global.Portal.AuthServiceReference.GetSystemUserByLoginNameRequest inValue = new WMS.Global.Portal.AuthServiceReference.GetSystemUserByLoginNameRequest();
            inValue.Body = new WMS.Global.Portal.AuthServiceReference.GetSystemUserByLoginNameRequestBody();
            inValue.Body.loginName = loginName;
            WMS.Global.Portal.AuthServiceReference.GetSystemUserByLoginNameResponse retVal = ((WMS.Global.Portal.AuthServiceReference.AuthServiceSoap)(this)).GetSystemUserByLoginName(inValue);
            return retVal.Body.GetSystemUserByLoginNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WMS.Global.Portal.AuthServiceReference.GetSystemUserByLoginNameResponse> WMS.Global.Portal.AuthServiceReference.AuthServiceSoap.GetSystemUserByLoginNameAsync(WMS.Global.Portal.AuthServiceReference.GetSystemUserByLoginNameRequest request) {
            return base.Channel.GetSystemUserByLoginNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<WMS.Global.Portal.AuthServiceReference.GetSystemUserByLoginNameResponse> GetSystemUserByLoginNameAsync(string loginName) {
            WMS.Global.Portal.AuthServiceReference.GetSystemUserByLoginNameRequest inValue = new WMS.Global.Portal.AuthServiceReference.GetSystemUserByLoginNameRequest();
            inValue.Body = new WMS.Global.Portal.AuthServiceReference.GetSystemUserByLoginNameRequestBody();
            inValue.Body.loginName = loginName;
            return ((WMS.Global.Portal.AuthServiceReference.AuthServiceSoap)(this)).GetSystemUserByLoginNameAsync(inValue);
        }
    }
}
