//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBK.AuthServiceUtil.AuthServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemUserBase", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NBK.AuthServiceUtil.AuthServiceReference.SystemUser))]
    public partial class SystemUserBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int SysNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisplayNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        private NBK.AuthServiceUtil.AuthServiceReference.UserStatus StatusField;
        
        private int InUserField;
        
        private System.DateTime InDateField;
        
        private int EditUserField;
        
        private System.DateTime EditDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int SysNO {
            get {
                return this.SysNOField;
            }
            set {
                if ((this.SysNOField.Equals(value) != true)) {
                    this.SysNOField = value;
                    this.RaisePropertyChanged("SysNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string LoginName {
            get {
                return this.LoginNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginNameField, value) != true)) {
                    this.LoginNameField = value;
                    this.RaisePropertyChanged("LoginName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DisplayName {
            get {
                return this.DisplayNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplayNameField, value) != true)) {
                    this.DisplayNameField = value;
                    this.RaisePropertyChanged("DisplayName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string DepartmentName {
            get {
                return this.DepartmentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentNameField, value) != true)) {
                    this.DepartmentNameField = value;
                    this.RaisePropertyChanged("DepartmentName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public NBK.AuthServiceUtil.AuthServiceReference.UserStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int InUser {
            get {
                return this.InUserField;
            }
            set {
                if ((this.InUserField.Equals(value) != true)) {
                    this.InUserField = value;
                    this.RaisePropertyChanged("InUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.DateTime InDate {
            get {
                return this.InDateField;
            }
            set {
                if ((this.InDateField.Equals(value) != true)) {
                    this.InDateField = value;
                    this.RaisePropertyChanged("InDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int EditUser {
            get {
                return this.EditUserField;
            }
            set {
                if ((this.EditUserField.Equals(value) != true)) {
                    this.EditUserField = value;
                    this.RaisePropertyChanged("EditUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public System.DateTime EditDate {
            get {
                return this.EditDateField;
            }
            set {
                if ((this.EditDateField.Equals(value) != true)) {
                    this.EditDateField = value;
                    this.RaisePropertyChanged("EditDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemUser", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SystemUser : NBK.AuthServiceUtil.AuthServiceReference.SystemUserBase {
        
        private int CompanySysNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CompanySysNO {
            get {
                return this.CompanySysNOField;
            }
            set {
                if ((this.CompanySysNOField.Equals(value) != true)) {
                    this.CompanySysNOField = value;
                    this.RaisePropertyChanged("CompanySysNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CompanyCode {
            get {
                return this.CompanyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyCodeField, value) != true)) {
                    this.CompanyCodeField = value;
                    this.RaisePropertyChanged("CompanyCode");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserStatus", Namespace="urn:Newegg.authcenter")]
    public enum UserStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Disabled = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Enabled = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemRole", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SystemRole : NBK.AuthServiceUtil.AuthServiceReference.SystemRoleBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApplicationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NBK.AuthServiceUtil.AuthServiceReference.SystemFunction[] FunctionListField;
        
        private bool UserHadField;
        
        private int CompanySysNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ApplicationName {
            get {
                return this.ApplicationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationNameField, value) != true)) {
                    this.ApplicationNameField = value;
                    this.RaisePropertyChanged("ApplicationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public NBK.AuthServiceUtil.AuthServiceReference.SystemFunction[] FunctionList {
            get {
                return this.FunctionListField;
            }
            set {
                if ((object.ReferenceEquals(this.FunctionListField, value) != true)) {
                    this.FunctionListField = value;
                    this.RaisePropertyChanged("FunctionList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool UserHad {
            get {
                return this.UserHadField;
            }
            set {
                if ((this.UserHadField.Equals(value) != true)) {
                    this.UserHadField = value;
                    this.RaisePropertyChanged("UserHad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int CompanySysNO {
            get {
                return this.CompanySysNOField;
            }
            set {
                if ((this.CompanySysNOField.Equals(value) != true)) {
                    this.CompanySysNOField = value;
                    this.RaisePropertyChanged("CompanySysNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemRoleBase", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NBK.AuthServiceUtil.AuthServiceReference.SystemRole))]
    public partial class SystemRoleBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int SysNOField;
        
        private System.Guid ApplicationIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomConditionField;
        
        private System.Nullable<int> ParentRoleSysNOField;
        
        private NBK.AuthServiceUtil.AuthServiceReference.RoleStatus StatusField;
        
        private int InUserField;
        
        private System.DateTime InDateField;
        
        private int EditUserField;
        
        private System.DateTime EditDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int SysNO {
            get {
                return this.SysNOField;
            }
            set {
                if ((this.SysNOField.Equals(value) != true)) {
                    this.SysNOField = value;
                    this.RaisePropertyChanged("SysNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.Guid ApplicationID {
            get {
                return this.ApplicationIDField;
            }
            set {
                if ((this.ApplicationIDField.Equals(value) != true)) {
                    this.ApplicationIDField = value;
                    this.RaisePropertyChanged("ApplicationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string RoleName {
            get {
                return this.RoleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleNameField, value) != true)) {
                    this.RoleNameField = value;
                    this.RaisePropertyChanged("RoleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CustomCondition {
            get {
                return this.CustomConditionField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomConditionField, value) != true)) {
                    this.CustomConditionField = value;
                    this.RaisePropertyChanged("CustomCondition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<int> ParentRoleSysNO {
            get {
                return this.ParentRoleSysNOField;
            }
            set {
                if ((this.ParentRoleSysNOField.Equals(value) != true)) {
                    this.ParentRoleSysNOField = value;
                    this.RaisePropertyChanged("ParentRoleSysNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public NBK.AuthServiceUtil.AuthServiceReference.RoleStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int InUser {
            get {
                return this.InUserField;
            }
            set {
                if ((this.InUserField.Equals(value) != true)) {
                    this.InUserField = value;
                    this.RaisePropertyChanged("InUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.DateTime InDate {
            get {
                return this.InDateField;
            }
            set {
                if ((this.InDateField.Equals(value) != true)) {
                    this.InDateField = value;
                    this.RaisePropertyChanged("InDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int EditUser {
            get {
                return this.EditUserField;
            }
            set {
                if ((this.EditUserField.Equals(value) != true)) {
                    this.EditUserField = value;
                    this.RaisePropertyChanged("EditUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public System.DateTime EditDate {
            get {
                return this.EditDateField;
            }
            set {
                if ((this.EditDateField.Equals(value) != true)) {
                    this.EditDateField = value;
                    this.RaisePropertyChanged("EditDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoleStatus", Namespace="http://tempuri.org/")]
    public enum RoleStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Disabled = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Enabled = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemFunction", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SystemFunction : NBK.AuthServiceUtil.AuthServiceReference.SystemFunctionBase {
        
        private bool UserHadField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool UserHad {
            get {
                return this.UserHadField;
            }
            set {
                if ((this.UserHadField.Equals(value) != true)) {
                    this.UserHadField = value;
                    this.RaisePropertyChanged("UserHad");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemFunctionBase", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NBK.AuthServiceUtil.AuthServiceReference.SystemFunction))]
    public partial class SystemFunctionBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int SysNOField;
        
        private System.Guid ApplicationIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthKeyField;
        
        private NBK.AuthServiceUtil.AuthServiceReference.FunctionType TypeField;
        
        private NBK.AuthServiceUtil.AuthServiceReference.FunctionStatus StatusField;
        
        private int InUserField;
        
        private System.DateTime InDateField;
        
        private int EditUserField;
        
        private System.DateTime EditDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int SysNO {
            get {
                return this.SysNOField;
            }
            set {
                if ((this.SysNOField.Equals(value) != true)) {
                    this.SysNOField = value;
                    this.RaisePropertyChanged("SysNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.Guid ApplicationID {
            get {
                return this.ApplicationIDField;
            }
            set {
                if ((this.ApplicationIDField.Equals(value) != true)) {
                    this.ApplicationIDField = value;
                    this.RaisePropertyChanged("ApplicationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string AuthKey {
            get {
                return this.AuthKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthKeyField, value) != true)) {
                    this.AuthKeyField = value;
                    this.RaisePropertyChanged("AuthKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public NBK.AuthServiceUtil.AuthServiceReference.FunctionType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public NBK.AuthServiceUtil.AuthServiceReference.FunctionStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int InUser {
            get {
                return this.InUserField;
            }
            set {
                if ((this.InUserField.Equals(value) != true)) {
                    this.InUserField = value;
                    this.RaisePropertyChanged("InUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.DateTime InDate {
            get {
                return this.InDateField;
            }
            set {
                if ((this.InDateField.Equals(value) != true)) {
                    this.InDateField = value;
                    this.RaisePropertyChanged("InDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int EditUser {
            get {
                return this.EditUserField;
            }
            set {
                if ((this.EditUserField.Equals(value) != true)) {
                    this.EditUserField = value;
                    this.RaisePropertyChanged("EditUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public System.DateTime EditDate {
            get {
                return this.EditDateField;
            }
            set {
                if ((this.EditDateField.Equals(value) != true)) {
                    this.EditDateField = value;
                    this.RaisePropertyChanged("EditDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FunctionType", Namespace="http://tempuri.org/")]
    public enum FunctionType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Page = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Button = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FunctionStatus", Namespace="http://tempuri.org/")]
    public enum FunctionStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Disabled = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Enabled = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AuthServiceReference.AuthServiceSoap")]
    public interface AuthServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 loginName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        NBK.AuthServiceUtil.AuthServiceReference.LoginResponse Login(NBK.AuthServiceUtil.AuthServiceReference.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<NBK.AuthServiceUtil.AuthServiceReference.LoginResponse> LoginAsync(NBK.AuthServiceUtil.AuthServiceReference.LoginRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 loginName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TrustedLogin", ReplyAction="*")]
        NBK.AuthServiceUtil.AuthServiceReference.TrustedLoginResponse TrustedLogin(NBK.AuthServiceUtil.AuthServiceReference.TrustedLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TrustedLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<NBK.AuthServiceUtil.AuthServiceReference.TrustedLoginResponse> TrustedLoginAsync(NBK.AuthServiceUtil.AuthServiceReference.TrustedLoginRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 loginName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangePassword", ReplyAction="*")]
        NBK.AuthServiceUtil.AuthServiceReference.ChangePasswordResponse ChangePassword(NBK.AuthServiceUtil.AuthServiceReference.ChangePasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangePassword", ReplyAction="*")]
        System.Threading.Tasks.Task<NBK.AuthServiceUtil.AuthServiceReference.ChangePasswordResponse> ChangePasswordAsync(NBK.AuthServiceUtil.AuthServiceReference.ChangePasswordRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 applicationID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserFunction", ReplyAction="*")]
        NBK.AuthServiceUtil.AuthServiceReference.GetUserFunctionResponse GetUserFunction(NBK.AuthServiceUtil.AuthServiceReference.GetUserFunctionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserFunction", ReplyAction="*")]
        System.Threading.Tasks.Task<NBK.AuthServiceUtil.AuthServiceReference.GetUserFunctionResponse> GetUserFunctionAsync(NBK.AuthServiceUtil.AuthServiceReference.GetUserFunctionRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 applicationID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserAuthKey", ReplyAction="*")]
        NBK.AuthServiceUtil.AuthServiceReference.GetUserAuthKeyResponse GetUserAuthKey(NBK.AuthServiceUtil.AuthServiceReference.GetUserAuthKeyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserAuthKey", ReplyAction="*")]
        System.Threading.Tasks.Task<NBK.AuthServiceUtil.AuthServiceReference.GetUserAuthKeyResponse> GetUserAuthKeyAsync(NBK.AuthServiceUtil.AuthServiceReference.GetUserAuthKeyRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 applicationID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckUserFunction", ReplyAction="*")]
        NBK.AuthServiceUtil.AuthServiceReference.CheckUserFunctionResponse CheckUserFunction(NBK.AuthServiceUtil.AuthServiceReference.CheckUserFunctionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckUserFunction", ReplyAction="*")]
        System.Threading.Tasks.Task<NBK.AuthServiceUtil.AuthServiceReference.CheckUserFunctionResponse> CheckUserFunctionAsync(NBK.AuthServiceUtil.AuthServiceReference.CheckUserFunctionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public NBK.AuthServiceUtil.AuthServiceReference.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(NBK.AuthServiceUtil.AuthServiceReference.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string loginName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string loginName, string password) {
            this.loginName = loginName;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public NBK.AuthServiceUtil.AuthServiceReference.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(NBK.AuthServiceUtil.AuthServiceReference.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NBK.AuthServiceUtil.AuthServiceReference.SystemUser LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(NBK.AuthServiceUtil.AuthServiceReference.SystemUser LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TrustedLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TrustedLogin", Namespace="http://tempuri.org/", Order=0)]
        public NBK.AuthServiceUtil.AuthServiceReference.TrustedLoginRequestBody Body;
        
        public TrustedLoginRequest() {
        }
        
        public TrustedLoginRequest(NBK.AuthServiceUtil.AuthServiceReference.TrustedLoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TrustedLoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string loginName;
        
        public TrustedLoginRequestBody() {
        }
        
        public TrustedLoginRequestBody(string loginName) {
            this.loginName = loginName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TrustedLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TrustedLoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public NBK.AuthServiceUtil.AuthServiceReference.TrustedLoginResponseBody Body;
        
        public TrustedLoginResponse() {
        }
        
        public TrustedLoginResponse(NBK.AuthServiceUtil.AuthServiceReference.TrustedLoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TrustedLoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NBK.AuthServiceUtil.AuthServiceReference.SystemUser TrustedLoginResult;
        
        public TrustedLoginResponseBody() {
        }
        
        public TrustedLoginResponseBody(NBK.AuthServiceUtil.AuthServiceReference.SystemUser TrustedLoginResult) {
            this.TrustedLoginResult = TrustedLoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangePasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangePassword", Namespace="http://tempuri.org/", Order=0)]
        public NBK.AuthServiceUtil.AuthServiceReference.ChangePasswordRequestBody Body;
        
        public ChangePasswordRequest() {
        }
        
        public ChangePasswordRequest(NBK.AuthServiceUtil.AuthServiceReference.ChangePasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChangePasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string loginName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string oldPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string newPassword;
        
        public ChangePasswordRequestBody() {
        }
        
        public ChangePasswordRequestBody(string loginName, string oldPassword, string newPassword) {
            this.loginName = loginName;
            this.oldPassword = oldPassword;
            this.newPassword = newPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangePasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangePasswordResponse", Namespace="http://tempuri.org/", Order=0)]
        public NBK.AuthServiceUtil.AuthServiceReference.ChangePasswordResponseBody Body;
        
        public ChangePasswordResponse() {
        }
        
        public ChangePasswordResponse(NBK.AuthServiceUtil.AuthServiceReference.ChangePasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChangePasswordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NBK.AuthServiceUtil.AuthServiceReference.SystemUser ChangePasswordResult;
        
        public ChangePasswordResponseBody() {
        }
        
        public ChangePasswordResponseBody(NBK.AuthServiceUtil.AuthServiceReference.SystemUser ChangePasswordResult) {
            this.ChangePasswordResult = ChangePasswordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserFunctionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserFunction", Namespace="http://tempuri.org/", Order=0)]
        public NBK.AuthServiceUtil.AuthServiceReference.GetUserFunctionRequestBody Body;
        
        public GetUserFunctionRequest() {
        }
        
        public GetUserFunctionRequest(NBK.AuthServiceUtil.AuthServiceReference.GetUserFunctionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserFunctionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string applicationID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string loginName;
        
        public GetUserFunctionRequestBody() {
        }
        
        public GetUserFunctionRequestBody(string applicationID, string loginName) {
            this.applicationID = applicationID;
            this.loginName = loginName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserFunctionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserFunctionResponse", Namespace="http://tempuri.org/", Order=0)]
        public NBK.AuthServiceUtil.AuthServiceReference.GetUserFunctionResponseBody Body;
        
        public GetUserFunctionResponse() {
        }
        
        public GetUserFunctionResponse(NBK.AuthServiceUtil.AuthServiceReference.GetUserFunctionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserFunctionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NBK.AuthServiceUtil.AuthServiceReference.SystemRole[] GetUserFunctionResult;
        
        public GetUserFunctionResponseBody() {
        }
        
        public GetUserFunctionResponseBody(NBK.AuthServiceUtil.AuthServiceReference.SystemRole[] GetUserFunctionResult) {
            this.GetUserFunctionResult = GetUserFunctionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserAuthKeyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserAuthKey", Namespace="http://tempuri.org/", Order=0)]
        public NBK.AuthServiceUtil.AuthServiceReference.GetUserAuthKeyRequestBody Body;
        
        public GetUserAuthKeyRequest() {
        }
        
        public GetUserAuthKeyRequest(NBK.AuthServiceUtil.AuthServiceReference.GetUserAuthKeyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserAuthKeyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string applicationID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string loginName;
        
        public GetUserAuthKeyRequestBody() {
        }
        
        public GetUserAuthKeyRequestBody(string applicationID, string loginName) {
            this.applicationID = applicationID;
            this.loginName = loginName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserAuthKeyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserAuthKeyResponse", Namespace="http://tempuri.org/", Order=0)]
        public NBK.AuthServiceUtil.AuthServiceReference.GetUserAuthKeyResponseBody Body;
        
        public GetUserAuthKeyResponse() {
        }
        
        public GetUserAuthKeyResponse(NBK.AuthServiceUtil.AuthServiceReference.GetUserAuthKeyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserAuthKeyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NBK.AuthServiceUtil.AuthServiceReference.ArrayOfString GetUserAuthKeyResult;
        
        public GetUserAuthKeyResponseBody() {
        }
        
        public GetUserAuthKeyResponseBody(NBK.AuthServiceUtil.AuthServiceReference.ArrayOfString GetUserAuthKeyResult) {
            this.GetUserAuthKeyResult = GetUserAuthKeyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckUserFunctionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckUserFunction", Namespace="http://tempuri.org/", Order=0)]
        public NBK.AuthServiceUtil.AuthServiceReference.CheckUserFunctionRequestBody Body;
        
        public CheckUserFunctionRequest() {
        }
        
        public CheckUserFunctionRequest(NBK.AuthServiceUtil.AuthServiceReference.CheckUserFunctionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckUserFunctionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string applicationID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string authKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string loginName;
        
        public CheckUserFunctionRequestBody() {
        }
        
        public CheckUserFunctionRequestBody(string applicationID, string authKey, string loginName) {
            this.applicationID = applicationID;
            this.authKey = authKey;
            this.loginName = loginName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckUserFunctionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckUserFunctionResponse", Namespace="http://tempuri.org/", Order=0)]
        public NBK.AuthServiceUtil.AuthServiceReference.CheckUserFunctionResponseBody Body;
        
        public CheckUserFunctionResponse() {
        }
        
        public CheckUserFunctionResponse(NBK.AuthServiceUtil.AuthServiceReference.CheckUserFunctionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckUserFunctionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CheckUserFunctionResult;
        
        public CheckUserFunctionResponseBody() {
        }
        
        public CheckUserFunctionResponseBody(bool CheckUserFunctionResult) {
            this.CheckUserFunctionResult = CheckUserFunctionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AuthServiceSoapChannel : NBK.AuthServiceUtil.AuthServiceReference.AuthServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthServiceSoapClient : System.ServiceModel.ClientBase<NBK.AuthServiceUtil.AuthServiceReference.AuthServiceSoap>, NBK.AuthServiceUtil.AuthServiceReference.AuthServiceSoap {
        
        public AuthServiceSoapClient() {
        }
        
        public AuthServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NBK.AuthServiceUtil.AuthServiceReference.LoginResponse NBK.AuthServiceUtil.AuthServiceReference.AuthServiceSoap.Login(NBK.AuthServiceUtil.AuthServiceReference.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public NBK.AuthServiceUtil.AuthServiceReference.SystemUser Login(string loginName, string password) {
            NBK.AuthServiceUtil.AuthServiceReference.LoginRequest inValue = new NBK.AuthServiceUtil.AuthServiceReference.LoginRequest();
            inValue.Body = new NBK.AuthServiceUtil.AuthServiceReference.LoginRequestBody();
            inValue.Body.loginName = loginName;
            inValue.Body.password = password;
            NBK.AuthServiceUtil.AuthServiceReference.LoginResponse retVal = ((NBK.AuthServiceUtil.AuthServiceReference.AuthServiceSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NBK.AuthServiceUtil.AuthServiceReference.LoginResponse> NBK.AuthServiceUtil.AuthServiceReference.AuthServiceSoap.LoginAsync(NBK.AuthServiceUtil.AuthServiceReference.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<NBK.AuthServiceUtil.AuthServiceReference.LoginResponse> LoginAsync(string loginName, string password) {
            NBK.AuthServiceUtil.AuthServiceReference.LoginRequest inValue = new NBK.AuthServiceUtil.AuthServiceReference.LoginRequest();
            inValue.Body = new NBK.AuthServiceUtil.AuthServiceReference.LoginRequestBody();
            inValue.Body.loginName = loginName;
            inValue.Body.password = password;
            return ((NBK.AuthServiceUtil.AuthServiceReference.AuthServiceSoap)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NBK.AuthServiceUtil.AuthServiceReference.TrustedLoginResponse NBK.AuthServiceUtil.AuthServiceReference.AuthServiceSoap.TrustedLogin(NBK.AuthServiceUtil.AuthServiceReference.TrustedLoginRequest request) {
            return base.Channel.TrustedLogin(request);
        }
        
        public NBK.AuthServiceUtil.AuthServiceReference.SystemUser TrustedLogin(string loginName) {
            NBK.AuthServiceUtil.AuthServiceReference.TrustedLoginRequest inValue = new NBK.AuthServiceUtil.AuthServiceReference.TrustedLoginRequest();
            inValue.Body = new NBK.AuthServiceUtil.AuthServiceReference.TrustedLoginRequestBody();
            inValue.Body.loginName = loginName;
            NBK.AuthServiceUtil.AuthServiceReference.TrustedLoginResponse retVal = ((NBK.AuthServiceUtil.AuthServiceReference.AuthServiceSoap)(this)).TrustedLogin(inValue);
            return retVal.Body.TrustedLoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NBK.AuthServiceUtil.AuthServiceReference.TrustedLoginResponse> NBK.AuthServiceUtil.AuthServiceReference.AuthServiceSoap.TrustedLoginAsync(NBK.AuthServiceUtil.AuthServiceReference.TrustedLoginRequest request) {
            return base.Channel.TrustedLoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<NBK.AuthServiceUtil.AuthServiceReference.TrustedLoginResponse> TrustedLoginAsync(string loginName) {
            NBK.AuthServiceUtil.AuthServiceReference.TrustedLoginRequest inValue = new NBK.AuthServiceUtil.AuthServiceReference.TrustedLoginRequest();
            inValue.Body = new NBK.AuthServiceUtil.AuthServiceReference.TrustedLoginRequestBody();
            inValue.Body.loginName = loginName;
            return ((NBK.AuthServiceUtil.AuthServiceReference.AuthServiceSoap)(this)).TrustedLoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NBK.AuthServiceUtil.AuthServiceReference.ChangePasswordResponse NBK.AuthServiceUtil.AuthServiceReference.AuthServiceSoap.ChangePassword(NBK.AuthServiceUtil.AuthServiceReference.ChangePasswordRequest request) {
            return base.Channel.ChangePassword(request);
        }
        
        public NBK.AuthServiceUtil.AuthServiceReference.SystemUser ChangePassword(string loginName, string oldPassword, string newPassword) {
            NBK.AuthServiceUtil.AuthServiceReference.ChangePasswordRequest inValue = new NBK.AuthServiceUtil.AuthServiceReference.ChangePasswordRequest();
            inValue.Body = new NBK.AuthServiceUtil.AuthServiceReference.ChangePasswordRequestBody();
            inValue.Body.loginName = loginName;
            inValue.Body.oldPassword = oldPassword;
            inValue.Body.newPassword = newPassword;
            NBK.AuthServiceUtil.AuthServiceReference.ChangePasswordResponse retVal = ((NBK.AuthServiceUtil.AuthServiceReference.AuthServiceSoap)(this)).ChangePassword(inValue);
            return retVal.Body.ChangePasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NBK.AuthServiceUtil.AuthServiceReference.ChangePasswordResponse> NBK.AuthServiceUtil.AuthServiceReference.AuthServiceSoap.ChangePasswordAsync(NBK.AuthServiceUtil.AuthServiceReference.ChangePasswordRequest request) {
            return base.Channel.ChangePasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<NBK.AuthServiceUtil.AuthServiceReference.ChangePasswordResponse> ChangePasswordAsync(string loginName, string oldPassword, string newPassword) {
            NBK.AuthServiceUtil.AuthServiceReference.ChangePasswordRequest inValue = new NBK.AuthServiceUtil.AuthServiceReference.ChangePasswordRequest();
            inValue.Body = new NBK.AuthServiceUtil.AuthServiceReference.ChangePasswordRequestBody();
            inValue.Body.loginName = loginName;
            inValue.Body.oldPassword = oldPassword;
            inValue.Body.newPassword = newPassword;
            return ((NBK.AuthServiceUtil.AuthServiceReference.AuthServiceSoap)(this)).ChangePasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NBK.AuthServiceUtil.AuthServiceReference.GetUserFunctionResponse NBK.AuthServiceUtil.AuthServiceReference.AuthServiceSoap.GetUserFunction(NBK.AuthServiceUtil.AuthServiceReference.GetUserFunctionRequest request) {
            return base.Channel.GetUserFunction(request);
        }
        
        public NBK.AuthServiceUtil.AuthServiceReference.SystemRole[] GetUserFunction(string applicationID, string loginName) {
            NBK.AuthServiceUtil.AuthServiceReference.GetUserFunctionRequest inValue = new NBK.AuthServiceUtil.AuthServiceReference.GetUserFunctionRequest();
            inValue.Body = new NBK.AuthServiceUtil.AuthServiceReference.GetUserFunctionRequestBody();
            inValue.Body.applicationID = applicationID;
            inValue.Body.loginName = loginName;
            NBK.AuthServiceUtil.AuthServiceReference.GetUserFunctionResponse retVal = ((NBK.AuthServiceUtil.AuthServiceReference.AuthServiceSoap)(this)).GetUserFunction(inValue);
            return retVal.Body.GetUserFunctionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NBK.AuthServiceUtil.AuthServiceReference.GetUserFunctionResponse> NBK.AuthServiceUtil.AuthServiceReference.AuthServiceSoap.GetUserFunctionAsync(NBK.AuthServiceUtil.AuthServiceReference.GetUserFunctionRequest request) {
            return base.Channel.GetUserFunctionAsync(request);
        }
        
        public System.Threading.Tasks.Task<NBK.AuthServiceUtil.AuthServiceReference.GetUserFunctionResponse> GetUserFunctionAsync(string applicationID, string loginName) {
            NBK.AuthServiceUtil.AuthServiceReference.GetUserFunctionRequest inValue = new NBK.AuthServiceUtil.AuthServiceReference.GetUserFunctionRequest();
            inValue.Body = new NBK.AuthServiceUtil.AuthServiceReference.GetUserFunctionRequestBody();
            inValue.Body.applicationID = applicationID;
            inValue.Body.loginName = loginName;
            return ((NBK.AuthServiceUtil.AuthServiceReference.AuthServiceSoap)(this)).GetUserFunctionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NBK.AuthServiceUtil.AuthServiceReference.GetUserAuthKeyResponse NBK.AuthServiceUtil.AuthServiceReference.AuthServiceSoap.GetUserAuthKey(NBK.AuthServiceUtil.AuthServiceReference.GetUserAuthKeyRequest request) {
            return base.Channel.GetUserAuthKey(request);
        }
        
        public NBK.AuthServiceUtil.AuthServiceReference.ArrayOfString GetUserAuthKey(string applicationID, string loginName) {
            NBK.AuthServiceUtil.AuthServiceReference.GetUserAuthKeyRequest inValue = new NBK.AuthServiceUtil.AuthServiceReference.GetUserAuthKeyRequest();
            inValue.Body = new NBK.AuthServiceUtil.AuthServiceReference.GetUserAuthKeyRequestBody();
            inValue.Body.applicationID = applicationID;
            inValue.Body.loginName = loginName;
            NBK.AuthServiceUtil.AuthServiceReference.GetUserAuthKeyResponse retVal = ((NBK.AuthServiceUtil.AuthServiceReference.AuthServiceSoap)(this)).GetUserAuthKey(inValue);
            return retVal.Body.GetUserAuthKeyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NBK.AuthServiceUtil.AuthServiceReference.GetUserAuthKeyResponse> NBK.AuthServiceUtil.AuthServiceReference.AuthServiceSoap.GetUserAuthKeyAsync(NBK.AuthServiceUtil.AuthServiceReference.GetUserAuthKeyRequest request) {
            return base.Channel.GetUserAuthKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<NBK.AuthServiceUtil.AuthServiceReference.GetUserAuthKeyResponse> GetUserAuthKeyAsync(string applicationID, string loginName) {
            NBK.AuthServiceUtil.AuthServiceReference.GetUserAuthKeyRequest inValue = new NBK.AuthServiceUtil.AuthServiceReference.GetUserAuthKeyRequest();
            inValue.Body = new NBK.AuthServiceUtil.AuthServiceReference.GetUserAuthKeyRequestBody();
            inValue.Body.applicationID = applicationID;
            inValue.Body.loginName = loginName;
            return ((NBK.AuthServiceUtil.AuthServiceReference.AuthServiceSoap)(this)).GetUserAuthKeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NBK.AuthServiceUtil.AuthServiceReference.CheckUserFunctionResponse NBK.AuthServiceUtil.AuthServiceReference.AuthServiceSoap.CheckUserFunction(NBK.AuthServiceUtil.AuthServiceReference.CheckUserFunctionRequest request) {
            return base.Channel.CheckUserFunction(request);
        }
        
        public bool CheckUserFunction(string applicationID, string authKey, string loginName) {
            NBK.AuthServiceUtil.AuthServiceReference.CheckUserFunctionRequest inValue = new NBK.AuthServiceUtil.AuthServiceReference.CheckUserFunctionRequest();
            inValue.Body = new NBK.AuthServiceUtil.AuthServiceReference.CheckUserFunctionRequestBody();
            inValue.Body.applicationID = applicationID;
            inValue.Body.authKey = authKey;
            inValue.Body.loginName = loginName;
            NBK.AuthServiceUtil.AuthServiceReference.CheckUserFunctionResponse retVal = ((NBK.AuthServiceUtil.AuthServiceReference.AuthServiceSoap)(this)).CheckUserFunction(inValue);
            return retVal.Body.CheckUserFunctionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NBK.AuthServiceUtil.AuthServiceReference.CheckUserFunctionResponse> NBK.AuthServiceUtil.AuthServiceReference.AuthServiceSoap.CheckUserFunctionAsync(NBK.AuthServiceUtil.AuthServiceReference.CheckUserFunctionRequest request) {
            return base.Channel.CheckUserFunctionAsync(request);
        }
        
        public System.Threading.Tasks.Task<NBK.AuthServiceUtil.AuthServiceReference.CheckUserFunctionResponse> CheckUserFunctionAsync(string applicationID, string authKey, string loginName) {
            NBK.AuthServiceUtil.AuthServiceReference.CheckUserFunctionRequest inValue = new NBK.AuthServiceUtil.AuthServiceReference.CheckUserFunctionRequest();
            inValue.Body = new NBK.AuthServiceUtil.AuthServiceReference.CheckUserFunctionRequestBody();
            inValue.Body.applicationID = applicationID;
            inValue.Body.authKey = authKey;
            inValue.Body.loginName = loginName;
            return ((NBK.AuthServiceUtil.AuthServiceReference.AuthServiceSoap)(this)).CheckUserFunctionAsync(inValue);
        }
    }
}
